### PR TITLE
fixed incompatibility with some anti-bots.

### PR DESCRIPTION
**Pull request by gameszaum**
I found it out some antibots that use ChannelWrapper to register some packets too, and It was causing an massive error when protocolize tries to get your own data on ChannelWrapper.

### CODE REVIEW

**Review by Exceptionflug — COMMENTED** [review]
Can you please explain which essential changes you've made, since there are a lot of reformatting changes in this commit

**Comment by gameszaum** [comment]
Alright, in ProtocolizeDecoderChannelHandler constructor I have created a try catch to get Object from ChannelWrapper and in NettyPipelineInjector I have changed method's injectAfter and injectBefore.

image
image
image

**Comment by Exceptionflug** [comment]
Is it on purpose that you suppress all exceptions in injectAfter and injectBefore?

**Comment by gameszaum** [comment]
Yes, I saw an antibot printing a log error, but still working fine with all functions, I'm talking with his dev to fix this on the future.

**Comment by Exceptionflug** [comment]
Yeah but it is bad practice to suppress exceptions at all. Please log this at least at DEBUG or FINEST level.

**Comment by KotlinFactory** [comment]
Any updates on your site @gameszaum

**Pull request closed without merging**
